version: '3'

services:
  ranbam:
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - .:/home/developer/workspace
    user: developer
    working_dir: /home/developer/workspace    
    entrypoint: /bin/bash
