list(APPEND
  ASSIMP_CMAKE_ARGS
  "-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}"
  "-DASSIMP_DOUBLE_PRECISION=ON"
  "-DASSIMP_BUILD_TESTS=OFF"
  "-DASSIMP_BUILD_ASSIMP_TOOLS=OFF"
)

ExternalProject_Add(dependency_assimp
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/assimp
  CMAKE_ARGS ${ASSIMP_CMAKE_ARGS}
  BUILD_COMMAND $(MAKE)
  INSTALL_COMMAND $(MAKE) install
)
