set(BREAKPAD_SOURCE_DIRECTORY ${CMAKE_SOURCE_DIR}/dependencies/breakpad/src)
set(BREAKPAD_CONFIGURE_EXECUTABLE ${BREAKPAD_SOURCE_DIRECTORY}/configure)

ExternalProject_Add(dependency_breakpad
  SOURCE_DIR
    ${BREAKPAD_SOURCE_DIRECTORY}
  CONFIGURE_COMMAND
    ${BREAKPAD_CONFIGURE_EXECUTABLE} --prefix=${CMAKE_INSTALL_PREFIX}
  BUILD_COMMAND
    $(MAKE)
  INSTALL_COMMAND
    $(MAKE) install
)
