list(APPEND
  BULLET3_CMAKE_ARGS
  "-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}"
  "-DUSE_DOUBLE_PRECISION=ON"
  "-DUSE_GLUT=OFF"
  "-DUSE_GRAPHICAL_BENCHMARK=OFF"
  "-DBUILD_SHARED_LIBS=ON"
  "-DBUILD_ENET=OFF"
  "-DBUILD_CLSOCKET=OFF"
  "-DBUILD_OPENGL3_DEMOS=OFF"
  "-DBUILD_BULLET2_DEMOS=OFF"
  "-DBUILD_PYBULLET=OFF"
  "-DBUILD_UNIT_TESTS=OFF"
  "-DBUILD_EGL=OFF"
)

ExternalProject_Add(dependency_bullet3
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/bullet3
  CMAKE_ARGS ${BULLET3_CMAKE_ARGS}
  BUILD_COMMAND $(MAKE)
  INSTALL_COMMAND $(MAKE) install
)
