list(APPEND
  CEGUI_CMAKE_ARGS
  "-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}"
)

ExternalProject_Add(dependency_cegui
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/cegui
  CMAKE_ARGS ${CEGUI_CMAKE_ARGS}
  BUILD_COMMAND $(MAKE)
  INSTALL_COMMAND $(MAKE) install
  
)
