list(APPEND
  EIGEN_CMAKE_ARGS
  "-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}"
  "-DEIGEN_BUILD_PKGCONFIG=OFF"
  "-DEIGEN_TEST_CXX11=ON"
)

ExternalProject_Add(dependency_eigen
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/eigen
  CMAKE_ARGS ${EIGEN_CMAKE_ARGS}
  BUILD_COMMAND $(MAKE)
  INSTALL_COMMAND $(MAKE) install
)
