list(APPEND
  GLM_CMAKE_ARGS
  "-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}"
  "-DGLM_STATIC_LIBRARY_ENABLE=OFF"
  "-DGLM_DYNAMIC_LIBRARY_ENABLE=OFF"
  "-DGLM_TEST_ENABLE=OFF"
)

ExternalProject_Add(dependency_glm
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/glm
  CMAKE_ARGS ${GLM_CMAKE_ARGS}
  BUILD_COMMAND $(MAKE)
  INSTALL_COMMAND $(MAKE) install
)
