list(APPEND
  GOOGLETEST_CMAKE_ARGS
  "-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}"
)

ExternalProject_Add(dependency_googletest
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/googletest
  CMAKE_ARGS ${GOOGLETEST_CMAKE_ARGS}
  BUILD_COMMAND $(MAKE)
  INSTALL_COMMAND $(MAKE) install
)
