list(APPEND
  SPDLOG_CMAKE_ARGS
  "-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}"
  "-DSPDLOG_BUILD_EXAMPLES=OFF"
  "-DSPDLOG_BUILD_TESTING=OFF"
)

ExternalProject_Add(dependency_spdlog
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/spdlog
  CMAKE_ARGS ${SPDLOG_CMAKE_ARGS}
  BUILD_COMMAND $(MAKE)
  INSTALL_COMMAND $(MAKE) install
)
